// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: pb/OddLookup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OddOrEven struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOdd []bool `protobuf:"varint,1,rep,packed,name=is_odd,json=isOdd,proto3" json:"is_odd,omitempty"`
}

func (x *OddOrEven) Reset() {
	*x = OddOrEven{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_OddLookup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OddOrEven) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OddOrEven) ProtoMessage() {}

func (x *OddOrEven) ProtoReflect() protoreflect.Message {
	mi := &file_pb_OddLookup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OddOrEven.ProtoReflect.Descriptor instead.
func (*OddOrEven) Descriptor() ([]byte, []int) {
	return file_pb_OddLookup_proto_rawDescGZIP(), []int{0}
}

func (x *OddOrEven) GetIsOdd() []bool {
	if x != nil {
		return x.IsOdd
	}
	return nil
}

type CompressedLayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sections []*CompressedSection `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
}

func (x *CompressedLayer) Reset() {
	*x = CompressedLayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_OddLookup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompressedLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressedLayer) ProtoMessage() {}

func (x *CompressedLayer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_OddLookup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressedLayer.ProtoReflect.Descriptor instead.
func (*CompressedLayer) Descriptor() ([]byte, []int) {
	return file_pb_OddLookup_proto_rawDescGZIP(), []int{1}
}

func (x *CompressedLayer) GetSections() []*CompressedSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type CompressedSection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start   uint64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End     uint64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CompressedSection) Reset() {
	*x = CompressedSection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_OddLookup_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompressedSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressedSection) ProtoMessage() {}

func (x *CompressedSection) ProtoReflect() protoreflect.Message {
	mi := &file_pb_OddLookup_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressedSection.ProtoReflect.Descriptor instead.
func (*CompressedSection) Descriptor() ([]byte, []int) {
	return file_pb_OddLookup_proto_rawDescGZIP(), []int{2}
}

func (x *CompressedSection) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *CompressedSection) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *CompressedSection) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_pb_OddLookup_proto protoreflect.FileDescriptor

var file_pb_OddLookup_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x4f, 0x64, 0x64, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x09, 0x4f, 0x64, 0x64, 0x4f, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x6f, 0x64, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x08, 0x52, 0x05, 0x69, 0x73, 0x4f, 0x64, 0x64, 0x22, 0x41, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x08, 0x73,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x55, 0x0a, 0x11, 0x43,
	0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4d, 0x61, 0x6e, 0x62, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x2f, 0x6c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x2d, 0x6f, 0x64, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_OddLookup_proto_rawDescOnce sync.Once
	file_pb_OddLookup_proto_rawDescData = file_pb_OddLookup_proto_rawDesc
)

func file_pb_OddLookup_proto_rawDescGZIP() []byte {
	file_pb_OddLookup_proto_rawDescOnce.Do(func() {
		file_pb_OddLookup_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_OddLookup_proto_rawDescData)
	})
	return file_pb_OddLookup_proto_rawDescData
}

var file_pb_OddLookup_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_OddLookup_proto_goTypes = []interface{}{
	(*OddOrEven)(nil),         // 0: OddOrEven
	(*CompressedLayer)(nil),   // 1: CompressedLayer
	(*CompressedSection)(nil), // 2: CompressedSection
}
var file_pb_OddLookup_proto_depIdxs = []int32{
	2, // 0: CompressedLayer.sections:type_name -> CompressedSection
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_OddLookup_proto_init() }
func file_pb_OddLookup_proto_init() {
	if File_pb_OddLookup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_OddLookup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OddOrEven); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_OddLookup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompressedLayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_OddLookup_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompressedSection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_OddLookup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_OddLookup_proto_goTypes,
		DependencyIndexes: file_pb_OddLookup_proto_depIdxs,
		MessageInfos:      file_pb_OddLookup_proto_msgTypes,
	}.Build()
	File_pb_OddLookup_proto = out.File
	file_pb_OddLookup_proto_rawDesc = nil
	file_pb_OddLookup_proto_goTypes = nil
	file_pb_OddLookup_proto_depIdxs = nil
}
